#!/bin/bash
make clean
#
# The "big two" standard bootloaders.
make atmega328
make atmega328_ethernet
make atmega2560
#make atmega8
#make atmega168
#make debug328
#
# additional buildable platforms of
#  somewhat questionable support level
#make lilypad
#make lilypad_resonator
#make pro8
#make pro16
#make pro20
#make atmega328_pro8
#make sanguino
#make mega
#make atmega88
#make luminet
