#!groovy
@Library('jenkins-pipeline-lib') _

pipeline
{
  agent any
  options
  {
    buildDiscarder(BuildHistoryManager([
      [
        conditions: [
            BuildResult(matchAborted: true)
        ],
        actions: [DeleteBuild()]
      ]
    ]))
  }
  environment
  {
    GIT_CHANGE_LOG = gitChangeLog(currentBuild.changeSets)
  }
  parameters
  {
    string(defaultValue: '11', description: 'Major version number (x.0.0)', name: 'MAJOR_VERSION')
    string(defaultValue: '3', description: 'Minor version number (0.x.0)', name: 'MINOR_VERSION')
  }
  triggers
  {
    //At 04:00 on every day-of-week from Monday through Friday.
    pollSCM('H 4 * * 1-5')
  }
  stages
  {
    stage('Setup')
    {
      steps
      {
        echo 'Checking to see if we need to do this build'
        script {
          try {
            sh "tools/check_nightly_build_need.sh"
          } catch (Exception e) {
            currentBuild.result = 'ABORTED'
            error('Aborting, no changes since last nightly build.')
          }
        }

        echo 'Running make clean...'
        sh 'make distclean'

        gitTagPreBuild "${params.MAJOR_VERSION}.${params.MINOR_VERSION}.${BUILD_NUMBER}"
      }
    }
    stage('Build')
    {
      steps
      {
        sh 'make'
      }
    }
    stage('Package')
    {
      steps
      {
        sh 'make package'
        sh 'git checkout master'
        sh 'git pull'
        sh 'git add package_athena-bootloader_index.json'
        sh "git commit -m 'Generate package_athena-bootloader_index.json for ${params.MAJOR_VERSION}.${params.MINOR_VERSION}.${BUILD_NUMBER}'"
        sh "git push"
      }
    }
    stage('Archive')
    {
      steps
      {
        echo 'Archiving artifacts'
        dir('buildresults/release')
        {
          archiveArtifacts 'athena_bootloaders-*'
        }
      }
      post
      {
        failure
        {
          sendNotifications 'ARCHIVE_ERROR'
        }
      }
    }
  }
  post
  {
    always
    {
      // Scan for open tasks, warnings, issues, etc.
      recordIssues(
        enabledForFailure: true,
        healthy: 5,
        unhealthy: 10,
        referenceJobName: 'ea-nightly/libmemory/master',
        qualityGates: [
          // 3 new issue: unstable
          [threshold: 15, type: 'DELTA', unstable: true],
          // 5 new issues: failed build
          [threshold: 15, type: 'DELTA', unstable: false],
          // 10 total issues: unstable
          [threshold: 15, type: 'TOTAL', unstable: true],
          // 20 total issues: fail
          [threshold: 15, type: 'TOTAL', unstable: false]
        ],
        tools: [
          // TODO: re-enable: clang(),
          taskScanner(
            excludePattern: 'buildresults/**, dependencies/**, build/**',
            includePattern: '**/*.c, **/*.cpp, **/*.h, **/*.hpp, **/*.lua, **/*.sh, **/*.build',
            normalTags: 'TODO, to do, WIP',
            highTags: 'FIXME, FIX',
            ignoreCase: true,
          ),
          //cppCheck(
          //  pattern: 'buildresults/**/cppcheck.xml',
          //),
        ]
      )

      // Report Status
      slackNotify(currentBuild.currentResult)
      gitTagCleanup "${params.MAJOR_VERSION}.${params.MINOR_VERSION}.${BUILD_NUMBER}"
    }
    success
    {
      githubSetConfig('69e4682e-2951-492f-b828-da06364c322d')
      // Release step creates a tag
      gitTagSuccess "${params.MAJOR_VERSION}.${params.MINOR_VERSION}.${BUILD_NUMBER}"
      githubUploadRelease("${params.MAJOR_VERSION}.${params.MINOR_VERSION}.${BUILD_NUMBER}",
        'buildresults/release/*.zip')
    }
    failure
    {
      /*
      * This job does not have a GitHub configuration,
      * so we need to create a dummy config
      */
      githubSetConfig('69e4682e-2951-492f-b828-da06364c322d')
      githubFileIssue()
      emailNotify(currentBuild.currentResult)
    }
  }
}
